### ISSUE TITLE
MicroView License expired

### ISSUE THREAD

**Issue by bongjaejun** [parallaxinnovations/MicroView#46]
Most recent version does not work any more due to expiration on 2/1/2020. I cannot use Advanced ROI. Any update coming soon?

**Comment by capagani** [comment]
Having a similar issue. Please update!

**Comment by hrasheed53** [comment]
Me as well!!

**Comment by jeremy-gill** [comment]
Sorry for the delay - problems with Mac digital signing delayed this release.  New binaries have now been uploaded that extend the demo and add few new features as per the [changelog](https://microview.parallax-innovations.com/changelog/).
